# Generated by Django 2.2 on 2019-05-01 11:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Wilderness', 'Wilderness'), ('Religious', 'Religious'), ('Mountain', 'Mountain'), ('Trekking', 'Trekking'), ('Adventure', 'Adventure')], default=True, max_length=48),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default=0, max_length='1000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=17),
        ),
        migrations.AlterField(
            model_name='myrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
