# Generated by Django 2.2 on 2019-05-01 12:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20190501_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Wilderness', 'Wilderness'), ('Religious', 'Religious'), ('Mountain', 'Mountain'), ('Trekking', 'Trekking'), ('Adventure', 'Adventure')], max_length=48),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
