# Generated by Django 2.2 on 2019-05-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20190501_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='itinerary',
            field=models.TextField(max_length=1000),
        ),
    ]
