# Generated by Django 2.2 on 2019-05-01 12:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20190501_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.AddField(
            model_name='tourist',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=0, max_length=17),
            preserve_default=False,
        ),
    ]
