# Generated by Django 2.2 on 2019-05-01 12:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20190501_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=1, max_length=17),
        ),
    ]
