# Generated by Django 2.2 on 2019-05-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20190501_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default=0, upload_to='photo', verbose_name='My Photo'),
            preserve_default=False,
        ),
    ]
