# Generated by Django 2.2 on 2019-05-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='photo', verbose_name='Place image'),
        ),
    ]
