# Generated by Django 2.2 on 2019-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20190501_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
