# Generated by Django 2.2 on 2019-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20190502_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Contact', models.IntegerField(max_length=11)),
                ('website', models.CharField(max_length=20)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
