# Generated by Django 2.2 on 2019-05-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_auto_20190503_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='photo', verbose_name='Place image'),
            preserve_default=False,
        ),
    ]
